version: '3.3'

services:
  postgres:
    image: postgres
    restart: always
    command: -c wal_level=logical -c max_wal_senders=10 -c max_replication_slots=10
    build:
       context: ./postgres-sql/
    ports:
       - "5432:5432"
    environment:
      POSTGRES_PASSWORD: tallest-tree 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  postgraphile:
      restart: always
      depends_on:
         - postgres
      build:
         context: ./postgraphile/
      ports:
         - "5000:5000"


